// Translations for the Post Property page.
// Extracted here to keep the page component lean.

export type PostPropertyContent = ReturnType<typeof getPostPropertyContent>["en"];

export function getPostPropertyContent(userName: string) {
  const hi = userName || "there";
  const salut = userName || "là";

  return {
    en: {
      greeting: `Hi ${hi},`,
      // Step 1
      step1Title: "Property Type & Basic Information",
      postingFor: "You are posting Your property for",
      pg: "PG",
      tenant: "Tenant",
      postingPGAs: "You are posting this PG as",
      postingTenantAs: "You are posting this Property as",
      owner: "Owner",
      propertyManager: "Property Manager",
      agent: "Agent",
      propertyCategory: "Property Category",
      villa: "Villa",
      flat: "Flat",
      house: "House",
      penthouse: "Penthouse",
      cityTitle: "City where your PG is located?",
      cityTitleTenant: "City where your Property is located?",
      citySubtitle: "Make sure you enter the correct address for a Verification",
      cityPlaceholder: "Ah",
      // Step 2
      step2Title: "Property Details",
      addressTitle: "Enter Your PG Address",
      tenantAddressTitle: "Enter Your Property Address",
      addressSubtitle: "Make sure the address is correct, complete and precise",
      addressLabel: "Address",
      addressPlaceholder: "Enter Your Address",
      areaNameLabel: "Area / Locality",
      areaNamePlaceholder: "e.g. Navarangpura, Satellite, Bopal",
      stateLabel: "State",
      statePlaceholder: "e.g. Gujarat, Maharashtra",
      pincodeLabel: "Pincode",
      pincodePlaceholder: "Enter Your Pincode",
      landmarkLabel: "Landmark",
      landmarkPlaceholder: "Enter Your Landmark",
      googleMapLabel: "Google Map Link",
      googleMapPlaceholder: "Paste Google Maps link of your location",
      googleMapHelper: "Open Google Maps, search your location, click Share, and copy the link",
      operationalLabel: "PG Operational Since",
      operationalPlaceholder: "Enter Your PG Operational Since",
      presentInLabel: "PG Present In",
      presentInPlaceholder: "Select",
      independentBuilding: "An Independent Building",
      independentFlats: "An Independent Flats",
      pgSociety: "Present In A Society",
      pgNameLabel: "PG Name",
      pgNamePlaceholder: "Enter Your PG Name",
      roomCategoriesTitle: "Room Categories in your PG",
      roomCategoriesSubtitle: "Select all the available room categories",
      single: "Single",
      double: "Double",
      triple: "Triple",
      four: "Four",
      other: "Other",
      roomDetailsFor: "Room Details For",
      numberOfRooms: "No. Of Rooms In PG",
      numberOfRoomsPlaceholder: "Enter Number",
      monthlyRent: "Monthly Rent Per Bed",
      monthlyRentPlaceholder: "Enter Amount",
      securityDeposit: "Security Deposit Per Bed",
      securityDepositPlaceholder: "Enter Amount",
      roomFacilities: "Room Facilities",
      // Tenant property details
      flatsInProject: "No. of flats in project/Society",
      lessThan50: "<50",
      fiftyTo100: "50-100",
      moreThan100: ">100",
      bedroom: "Bedroom",
      bathroom: "Bathroom",
      balconyOptional: "Balcony(Optional)",
      all: "All",
      onePlus: "1+",
      twoPlus: "2+",
      threePlus: "3+",
      fourPlus: "4+",
      totalFloorsInBuilding: "Total number of Floors in buildings",
      floorNoOfProperty: "Floor No. of your Property",
      furnishingLabel: "Furnishing",
      unfurnished: "Unfurnished",
      semiFurnished: "Semi-Furnished",
      fullyFurnished: "Fully-Furnished",
      areaLabel: "Area",
      min: "MIN",
      max: "MAX",
      enterMinArea: "Enter MIN Area",
      enterMaxArea: "Enter MAX Area",
      societyName: "Society",
      enterSocietyName: "Enter Society Name",
      // Step 3
      step3Title: "Pricing & Preferences",
      preferredGenderTitle: "Preferred Gender",
      male: "Male",
      female: "Female",
      both: "Both",
      tenantPreferencesTitle: "Tenant Preferences",
      professionals: "Professionals",
      students: "Students",
      pgRulesTitle: "PG Rules",
      guardianNotAllowed: "Guardian not allowed",
      nonVegFood: "Non-Veg Food",
      oppositeGender: "Opposite Gender",
      alcohol: "Alcohol",
      smoking: "Smoking",
      noticePeriodTitle: "Notice period",
      noticePeriodPlaceholder: "Select",
      oneWeek: "1 Week",
      fifteenDays: "15 Days",
      oneMonth: "1 Month",
      twoMonths: "2 Month",
      noNoticePeriod: "No Notice Period",
      gateClosingTitle: "Gate Closing time",
      gateClosingPlaceholder: "Select",
      servicesTitle: "Services Available",
      laundry: "Laundry",
      roomCleaning: "Room Cleaning",
      warden: "Warden",
      foodProvidedLabel: "Food Provided",
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      vegNonVegLabel: "Veg/Nonveg Food Provided",
      veg: "Veg",
      vegAndNonVeg: "Veg & Non Veg",
      foodChargesLabel: "Food Charges",
      includedInRent: "Included in rent",
      perMealBasis: "Per meal Basis",
      fixedMonthlyAmount: "Fixed monthly Amount",
      commonAreaTitle: "Common Area Amenities",
      fridge: "Fridge",
      kitchenSelfCooking: "Kitchen for Self-cooking",
      roWater: "RO Water",
      wiFi: "Wi-Fi",
      tv: "TV",
      powerBackup: "Power Backup",
      cctv: "CCTV",
      gymnasium: "Gymnasium",
      parkingAvailability: "Parking Availability",
      twoWheeler: "2-Wheeler",
      carParking: "Car Parking",
      // Tenant pricing
      priceExpectTitle: "Price you Expect",
      monthlyRentLabel: "Monthly Rent",
      enterMonthlyRent: "Enter Monthly Rent",
      securityAmountOptional: "Security Amount(Optional)",
      enterSecurityAmount: "Enter Security Amount",
      maintenanceChargesOptional: "Maintenance Charges(Optional)",
      selectMaintenanceType: "Select",
      statusOfProperty: "Status Of your Property",
      availableFrom: "Available From",
      selectedDate: "Selected Date",
      immediately: "Immediately",
      availableDate: "Available Date",
      additionalDetailsTitle: "Additional Details",
      additionalRooms: "Additional Rooms",
      poojaRoom: "Pooja Room",
      servantRoom: "Servant Room",
      store: "Store",
      study: "Study",
      overlookingLabel: "Overlooking",
      gardenPark: "Garden/Park",
      mainRoad: "Main Road",
      pool: "Pool",
      facingLabel: "Facing",
      east: "East",
      north: "North",
      northEast: "North-East",
      northWest: "North-West",
      south: "South",
      southEast: "South-East",
      southWest: "South-West",
      west: "West",
      societyAmenitiesLabel: "Society Amenities",
      tenantsYouPrefer: "Tenants you Prefer",
      coupleFamily: "Couple/Family",
      vegetarians: "Vegetarians",
      withCompanyLease: "With Company lease",
      withoutPets: "Without Pets",
      localityDescriptionLabel: "Locality Description",
      localityDescriptionPlaceholder: "Tell us what you like & dislike about this locality.",
      // Step 4
      step4Title: "Photos & Description",
      writeUSPTitle: "Write a USP about your property",
      selectCategoryLabel: "Select Category",
      selectCategoryPlaceholder: "Select",
      food: "Food",
      locality: "Locality",
      amenities: "Amenities",
      others: "Others",
      writeUSPLabel: "Write USP",
      writeUSPPlaceholder: "Write USP",
      pgDescriptionTitle: "Property Description",
      pgDescriptionSubtitle: "Write a brief description of your property",
      pgDescriptionLabel: "Description",
      pgDescriptionPlaceholder: "Enter Description",
      sampleDescription: "Sample Description",
      sample1: "Sample 1",
      sample2: "Sample 2",
      editAndUse: "Edit & Use",
      sampleText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      uploadPicturesTitle: "Upload Pictures",
      uploadSubtitle: "Property with Photos Get More Attention from Buyers",
      uploadInfo: "Accepted formats are .jpg, .jpeg, .gif, .bmp & .png | Minimum dimension allowed 600*400 Pixel | Maximum size allowed is 6 MB",
      roomsImages: "Rooms Images",
      roomsImagesSubtitle: "Upload images for each room and mark their availability status",
      tenantRoomsImages: "Room Images",
      tenantRoomsImagesSubtitle: "Upload images for each room in your property",
      addRoom: "Add Room",
      roomName: "Room Name",
      roomStatus: "Room Status",
      vacant: "Vacant",
      occupied: "Occupied",
      uploadRoomImage: "Upload Room Image",
      removeRoom: "Remove Room",
      kitchenImages: "Kitchen Images",
      washroomImages: "Washroom Images",
      commonAreaImages: "Common Area Images",
      view360Section: "360° Virtual Tour",
      view360Subtitle: "Add a 360° virtual tour link for better property showcase",
      view360Label: "360° View URL",
      view360Placeholder: "Enter 360° virtual tour link (e.g., Matterport, Google Street View)",
      uploadImages: "Upload Images",
      imagesUploaded: "images uploaded",
      singleRoom: "Single Room",
      buildingView: "Building View",
      commonArea: "Common Area",
      commonAmenities: "Common Amenities",
      kitchen: "Kitchen",
      neighbourhoodView: "Neighbourhood View",
      mapView: "Map View",
      // Success
      congratulations: "Congratulation..!",
      propertyPosted: "Your property has been posted Successfully!",
      // Common
      continue: "Continue",
      back: "Back",
      selectError: "Please select an option to continue",
      cityError: "Please select a city from suggestions",
      addressError: "Please fill all required fields",
      pgNameError: "Please enter PG name",
      roomCategoriesError: "Please select at least one room category",
      rentDetailsError: "Please fill all required fields",
      preferencesError: "Please select both preferences",
      uspError: "Please select category and write USP",
      descriptionError: "Please enter description",
      priceError: "Please enter monthly rent",
    },
    fr: {
      greeting: `Salut ${salut},`,
      step1Title: "Type de propriété et informations de base",
      postingFor: "Vous publiez votre propriété pour",
      pg: "PG",
      tenant: "Locataire",
      postingPGAs: "Vous publiez ce PG en tant que",
      postingTenantAs: "Vous publiez cette propriété en tant que",
      owner: "Propriétaire",
      propertyManager: "Gestionnaire immobilier",
      agent: "Agent",
      propertyCategory: "Catégorie de propriété",
      villa: "Villa",
      flat: "Appartement",
      house: "Maison",
      penthouse: "Penthouse",
      cityTitle: "Ville où se trouve votre PG?",
      cityTitleTenant: "Ville où se trouve votre propriété?",
      citySubtitle: "Assurez-vous d'entrer l'adresse correcte pour une vérification",
      cityPlaceholder: "Ah",
      step2Title: "Détails de la propriété",
      addressTitle: "Entrez l'adresse de votre PG",
      tenantAddressTitle: "Entrez l'adresse de votre propriété",
      addressSubtitle: "Assurez-vous que l'adresse est correcte, complète et précise",
      addressLabel: "Adresse",
      addressPlaceholder: "Entrez votre adresse",
      areaNameLabel: "Quartier / Localité",
      areaNamePlaceholder: "ex. Navarangpura, Satellite, Bopal",
      stateLabel: "État",
      statePlaceholder: "ex. Gujarat, Maharashtra",
      pincodeLabel: "Code postal",
      pincodePlaceholder: "Entrez votre code postal",
      landmarkLabel: "Point de repère",
      landmarkPlaceholder: "Entrez votre point de repère",
      googleMapLabel: "Lien Google Maps",
      googleMapPlaceholder: "Collez le lien Google Maps de votre emplacement",
      googleMapHelper: "Ouvrez Google Maps, recherchez votre emplacement, cliquez sur Partager et copiez le lien",
      operationalLabel: "PG opérationnel depuis",
      operationalPlaceholder: "Entrez depuis quand",
      presentInLabel: "PG présent dans",
      presentInPlaceholder: "Sélectionner",
      independentBuilding: "Un bâtiment indépendant",
      independentFlats: "Des appartements indépendants",
      pgSociety: "Présent dans une société",
      pgNameLabel: "Nom du PG",
      pgNamePlaceholder: "Entrez le nom de votre PG",
      roomCategoriesTitle: "Catégories de chambres dans votre PG",
      roomCategoriesSubtitle: "Sélectionnez toutes les catégories disponibles",
      single: "Simple",
      double: "Double",
      triple: "Triple",
      four: "Quatre",
      other: "Autre",
      roomDetailsFor: "Détails de la chambre pour",
      numberOfRooms: "Nombre de chambres dans PG",
      numberOfRoomsPlaceholder: "Entrez le nombre",
      monthlyRent: "Loyer mensuel par lit",
      monthlyRentPlaceholder: "Entrez le montant",
      securityDeposit: "Dépôt de garantie par lit",
      securityDepositPlaceholder: "Entrez le montant",
      roomFacilities: "Équipements de la chambre",
      flatsInProject: "Nombre d'appartements dans le projet",
      lessThan50: "<50",
      fiftyTo100: "50-100",
      moreThan100: ">100",
      bedroom: "Chambre",
      bathroom: "Salle de bain",
      balconyOptional: "Balcon(Optionnel)",
      all: "Tous",
      onePlus: "1+",
      twoPlus: "2+",
      threePlus: "3+",
      fourPlus: "4+",
      totalFloorsInBuilding: "Nombre total d'étages",
      floorNoOfProperty: "Numéro d'étage",
      furnishingLabel: "Ameublement",
      unfurnished: "Non meublé",
      semiFurnished: "Semi-meublé",
      fullyFurnished: "Entièrement meublé",
      areaLabel: "Zone",
      min: "MIN",
      max: "MAX",
      enterMinArea: "Entrez la zone MIN",
      enterMaxArea: "Entrez la zone MAX",
      societyName: "Société",
      enterSocietyName: "Entrez le nom de la société",
      step3Title: "Prix et préférences",
      preferredGenderTitle: "Genre préféré",
      male: "Homme",
      female: "Femme",
      both: "Les deux",
      tenantPreferencesTitle: "Préférences de locataire",
      professionals: "Professionnels",
      students: "Étudiants",
      pgRulesTitle: "Règles du PG",
      guardianNotAllowed: "Tuteur non autorisé",
      nonVegFood: "Nourriture non végétarienne",
      oppositeGender: "Sexe opposé",
      alcohol: "Alcool",
      smoking: "Fumer",
      noticePeriodTitle: "Période de préavis",
      noticePeriodPlaceholder: "Sélectionner",
      oneWeek: "1 semaine",
      fifteenDays: "15 jours",
      oneMonth: "1 mois",
      twoMonths: "2 mois",
      noNoticePeriod: "Pas de période de préavis",
      gateClosingTitle: "Heure de fermeture",
      gateClosingPlaceholder: "Sélectionner",
      servicesTitle: "Services disponibles",
      laundry: "Blanchisserie",
      roomCleaning: "Nettoyage de chambre",
      warden: "Gardien",
      foodProvidedLabel: "Nourriture fournie",
      breakfast: "Petit-déjeuner",
      lunch: "Déjeuner",
      dinner: "Dîner",
      vegNonVegLabel: "Nourriture végétarienne/non végétarienne",
      veg: "Végétarien",
      vegAndNonVeg: "Végétarien et non végétarien",
      foodChargesLabel: "Frais de nourriture",
      includedInRent: "Inclus dans le loyer",
      perMealBasis: "Par repas",
      fixedMonthlyAmount: "Montant mensuel fixe",
      commonAreaTitle: "Équipements des espaces communs",
      fridge: "Réfrigérateur",
      kitchenSelfCooking: "Cuisine pour cuisiner soi-même",
      roWater: "Eau RO",
      wiFi: "Wi-Fi",
      tv: "TV",
      powerBackup: "Alimentation de secours",
      cctv: "CCTV",
      gymnasium: "Gymnase",
      parkingAvailability: "Disponibilité du stationnement",
      twoWheeler: "Deux-roues",
      carParking: "Parking voiture",
      priceExpectTitle: "Prix que vous attendez",
      monthlyRentLabel: "Loyer mensuel",
      enterMonthlyRent: "Entrez le loyer mensuel",
      securityAmountOptional: "Montant de la caution(Optionnel)",
      enterSecurityAmount: "Entrez le montant",
      maintenanceChargesOptional: "Frais de maintenance(Optionnel)",
      selectMaintenanceType: "Sélectionner",
      statusOfProperty: "Statut de votre propriété",
      availableFrom: "Disponible à partir de",
      selectedDate: "Date sélectionnée",
      immediately: "Immédiatement",
      availableDate: "Date disponible",
      additionalDetailsTitle: "Détails supplémentaires",
      additionalRooms: "Chambres supplémentaires",
      poojaRoom: "Salle de prière",
      servantRoom: "Chambre de service",
      store: "Magasin",
      study: "Bureau",
      overlookingLabel: "Vue sur",
      gardenPark: "Jardin/Parc",
      mainRoad: "Route principale",
      pool: "Piscine",
      facingLabel: "Orientation",
      east: "Est",
      north: "Nord",
      northEast: "Nord-Est",
      northWest: "Nord-Ouest",
      south: "Sud",
      southEast: "Sud-Est",
      southWest: "Sud-Ouest",
      west: "Ouest",
      societyAmenitiesLabel: "Équipements de la société",
      tenantsYouPrefer: "Locataires que vous préférez",
      coupleFamily: "Couple/Famille",
      vegetarians: "Végétariens",
      withCompanyLease: "Avec bail d'entreprise",
      withoutPets: "Sans animaux",
      localityDescriptionLabel: "Description de la localité",
      localityDescriptionPlaceholder: "Dites-nous ce que vous aimez.",
      step4Title: "Photos et description",
      writeUSPTitle: "Écrivez un USP sur votre propriété",
      selectCategoryLabel: "Sélectionnez la catégorie",
      selectCategoryPlaceholder: "Sélectionner",
      food: "Nourriture",
      locality: "Localité",
      amenities: "Équipements",
      others: "Autres",
      writeUSPLabel: "Écrire USP",
      writeUSPPlaceholder: "Écrire USP",
      pgDescriptionTitle: "Description de la propriété",
      pgDescriptionSubtitle: "Rédigez une brève description",
      pgDescriptionLabel: "Description",
      pgDescriptionPlaceholder: "Entrez la description",
      sampleDescription: "Exemple de description",
      sample1: "Exemple 1",
      sample2: "Exemple 2",
      editAndUse: "Modifier et utiliser",
      sampleText: "Lorem Ipsum est simplement un texte factice.",
      uploadPicturesTitle: "Télécharger des photos",
      uploadSubtitle: "Les propriétés avec photos attirent plus l'attention",
      uploadInfo: "Formats acceptés: .jpg, .jpeg, .gif, .bmp et .png",
      roomsImages: "Images des chambres",
      roomsImagesSubtitle: "Téléchargez des images pour chaque chambre et marquez leur statut de disponibilité",
      tenantRoomsImages: "Images des chambres",
      tenantRoomsImagesSubtitle: "Téléchargez des images pour chaque chambre de votre propriété",
      addRoom: "Ajouter une chambre",
      roomName: "Nom de la chambre",
      roomStatus: "Statut de la chambre",
      vacant: "Vacant",
      occupied: "Occupé",
      uploadRoomImage: "Télécharger l'image de la chambre",
      removeRoom: "Supprimer la chambre",
      kitchenImages: "Images de la cuisine",
      washroomImages: "Images de la salle de bain",
      commonAreaImages: "Images de l'espace commun",
      view360Section: "Visite virtuelle 360°",
      view360Subtitle: "Ajoutez un lien de visite virtuelle 360° pour une meilleure présentation",
      view360Label: "URL de la vue 360°",
      view360Placeholder: "Entrez le lien de la visite virtuelle 360° (ex: Matterport, Google Street View)",
      uploadImages: "Télécharger des images",
      imagesUploaded: "images téléchargées",
      singleRoom: "Chambre simple",
      buildingView: "Vue du bâtiment",
      commonArea: "Espace commun",
      commonAmenities: "Équipements communs",
      kitchen: "Cuisine",
      neighbourhoodView: "Vue du quartier",
      mapView: "Vue de la carte",
      congratulations: "Félicitations..!",
      propertyPosted: "Votre propriété a été publiée avec succès!",
      continue: "Continuer",
      back: "Retour",
      selectError: "Veuillez sélectionner une option",
      cityError: "Veuillez sélectionner une ville",
      addressError: "Veuillez remplir tous les champs obligatoires",
      pgNameError: "Veuillez entrer le nom du PG",
      roomCategoriesError: "Veuillez sélectionner au moins une catégorie",
      rentDetailsError: "Veuillez remplir tous les champs obligatoires",
      preferencesError: "Veuillez sélectionner les deux préférences",
      uspError: "Veuillez sélectionner la catégorie et écrire l'USP",
      descriptionError: "Veuillez entrer la description",
      priceError: "Veuillez entrer le loyer mensuel",
    },
  };
}
